[package]
name = "salvo-admin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
salvo = { version = "0.74.2", features = ["affix-state"] }
tokio = { version = "1", features = ["macros"] }
#tracing = "0.1"
#tracing-subscriber = "0.3"

json = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

log = "0.4"
log4rs = "1.0"

sea-orm = { version = "1.0.1", features = ["sqlx-mysql", "runtime-async-std-native-tls", "with-chrono", "debug-print", "macros"] }
tracing-subscriber = "0.3.17"
dotenvy = "0.15.7"

jsonwebtoken = "9.3.0"

redis = "0.27.5"

futures = { version = "0.3", default-features = false }
thiserror = "2.0.3"

once_cell = "1.18.0"
